tools:
  php_loc:
    enabled: true
    excluded_dirs:
    - vendor
    - tests
    - install
  php_pdepend: true
  php_sim: true
  sensiolabs_security_checker: false
  external_code_coverage: false
  php_code_coverage: false
  php_cs_fixer:
    config:
      level: psr2
  php_mess_detector:
    enabled: true
    filter:
      paths:
      - 'assets/lib/*'
      - 'assets/snippets/*'
build:
  environment:
    php:
      version: 7.4
      ini:
        'date.timezone': 'Europe/Moscow'
    rabbitmq: false
    mysql: false
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
  tests:
    override:
    - php-scrutinizer-run
checks:
  php: true
filter:
  excluded_paths:
  - tests/*
  - install/*
  - assets/images/*
  - assets/js/*
  - assets/snippets/DLUsers/tpl/*
  - assets/snippets/DocLister/config/*
